#!/usr/bin/env bash
set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()    { echo -e "${BLUE}  →${NC} $*"; }
success() { echo -e "${GREEN}  ✓${NC} $*"; }
warn()    { echo -e "${YELLOW}  !${NC} $*"; }
die()     { echo -e "${RED}  ✗${NC} $*" >&2; exit 1; }

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   ⚡  Keeper Network  ·  Setup        ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════╝${NC}"
echo ""

# ── pre-flight ────────────────────────────────────────────────────────────────
docker info > /dev/null 2>&1 || die "Docker is not running. Start Docker Desktop and re-run."
docker compose version > /dev/null 2>&1 || die "docker compose not found. Install Docker Desktop v4+."
success "Docker is running"
echo ""

# ── existing .env ─────────────────────────────────────────────────────────────
if [ -f .env ]; then
  warn ".env already exists."
  read -rp "  Overwrite it and restart the keeper? [y/N] " overwrite
  [[ "$overwrite" =~ ^[Yy]$ ]] || { echo "  Aborted."; exit 0; }
  echo ""
fi

# ── network ───────────────────────────────────────────────────────────────────
echo -e "${BOLD}Step 1 of 3 — Choose network${NC}"
echo ""
PS3="  Network: "
select network in "Testnet (recommended)" "Mainnet"; do
  case $REPLY in
    1) RPC_URL="https://fullnode.testnet.sui.io:443"; break ;;
    2) RPC_URL="https://fullnode.mainnet.sui.io:443"; break ;;
    *) echo "  Enter 1 or 2." ;;
  esac
done
success "Network: $network  ($RPC_URL)"
echo ""

# ── private key ───────────────────────────────────────────────────────────────
echo -e "${BOLD}Step 2 of 3 — Sui private key${NC}"
echo ""
echo "  Your key is written only to the local .env file and never transmitted."
echo "  How to export:  sui keytool export --key-identity <alias>"
echo ""
while true; do
  read -rsp "  Private key: " SUI_PRIVATE_KEY
  echo ""
  [ -n "$SUI_PRIVATE_KEY" ] && break
  warn "Cannot be empty."
done
success "Private key accepted"
echo ""

# ── credential ID ─────────────────────────────────────────────────────────────
echo -e "${BOLD}Step 3 of 3 — KeeperCredential object ID${NC}"
echo ""
echo "  Bond 1 SUI on the dashboard to receive your credential object ID."
echo "  It looks like: 0x21b05605bbe..."
echo ""
while true; do
  read -rp "  Credential ID: " KEEPER_CREDENTIAL_ID
  [[ "$KEEPER_CREDENTIAL_ID" =~ ^0x[0-9a-fA-F]{40,}$ ]] && break
  warn "Must be a 0x-prefixed hex string. Try again."
done
success "Credential ID: ${KEEPER_CREDENTIAL_ID:0:18}…"
echo ""

# ── write .env ────────────────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by setup.sh — do not commit this file
SUI_PRIVATE_KEY=${SUI_PRIVATE_KEY}
KEEPER_CREDENTIAL_ID=${KEEPER_CREDENTIAL_ID}
SUI_RPC_URL=${RPC_URL}
KEEPER_REGISTRY_PKG=0x0fa6730cef35420714275ff33c8ab06bf600a4b459309ab93d2c2fc516496986
KEEPER_REGISTRY_ID=0x4c39bd48039b768fba38d6863acc8ca3c37a9ca3ce6c13e0f41399d6ade9bc90
DATABASE_URL=postgres://keeper:keeper@postgres:5432/keeper
KAFKA_BROKERS=kafka:9092
EOF

success ".env written"
echo ""

# ── launch ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}Starting keeper stack…${NC}"
echo "  (First run builds the image — this takes ~60 seconds)"
echo ""

docker compose pull --quiet 2>/dev/null || true
docker compose up -d --build

echo ""
echo -e "${GREEN}${BOLD}✓ Your keeper is live!${NC}"
echo ""
echo "  Watch settlements:   docker compose logs -f keeper"
echo "  Stop:                docker compose down"
echo "  Upgrade:             docker compose pull && docker compose up -d --build"
echo "  Check status:        docker compose ps"
echo ""
